version: "3"

tasks:
  generate:
      aliases:
        - migrate
      desc: "Database migration"
      cmds:
        - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations